# Generated by Django 4.0.4 on 2022-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_register_gender_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
